### ISSUE TITLE
Ошибка форматирования =)

### ISSUE THREAD

**Issue by iandreyshev** [Relz/ToDoList#17]
https://github.com/Relz/ToDoList/blob/115f9d094d9b6df1806b47166603799449e0b279/Server/src/ts/DataBase.ts#L5

- [ ] Приватные переменные должны начинаться с нижнего подчеркивания

Как правило переменная, которая хранит экземпляр singletone класса, называется instance

**Comment by Relz** [comment]
Исправил локально в ветке get-user-info
