### ISSUE TITLE
Большой шанс прострелить колено

### ISSUE THREAD

**Issue by iandreyshev** [Relz/ToDoList#18]
https://github.com/Relz/ToDoList/blob/115f9d094d9b6df1806b47166603799449e0b279/Server/src/ts/DataBase.ts#L43-L45

Разве не логичнее будет не кидать исключение при повторном создании базы, если она есть, а просто выйти из функции?

**Comment by Relz** [comment]
В ветке get-user-info провёл рефакторинг, теперь нет нужды в вызове метода init
